[package]
name = "graphql_client"
version = "0.6.1"
authors = ["Tom Houlé <tom@tomhoule.com>"]
description = "Typed GraphQL requests and responses"
repository = "https://github.com/graphql-rust/graphql-client"
license = "Apache-2.0 OR MIT"
keywords = ["graphql",  "api", "web", "webassembly", "wasm"]
categories = ["network-programming", "web-programming", "wasm"]

[dependencies]
failure = "0.1"
graphql_query_derive = {path = "../graphql_query_derive", version = "0.6.1" }
itertools = "0.7"
serde = "^1.0.78"
serde_derive = "1.0"
serde_json = "1.0"

[build-dependencies]
skeptic = "0.13"

[dev-dependencies]
skeptic = "0.13"
